name: pre-commit

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            software:
              - '!(Hardware/**)'
            hardware:
              - 'Hardware/**'
      - name: Ensure changelog is updated
        uses: dangoslen/changelog-enforcer@v3
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Show python version
        run: python --version
      - name: Install PlatformIO
        run: python -m pip install platformio
      - name: Check pre-commit hooks
        uses: pre-commit/action@v2.0.0
      - name: Build firmware
        run: platformio run
      - name: Build filesystem
        run: platformio run --target buildfs
      - name: Create artifacts
        run: |
          7z a SmartSpin2k.zip ./dist/*.*
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: .pio/build/*/SmartSpin2k.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: all-artifacts

      - name: Get tag info
        id: tag_info
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_info.outputs.SOURCE_TAG }}
          name: SmartSpin2k ${{ steps.tag_info.outputs.SOURCE_TAG }}
          draft: false
          prerelease: false
          body: ${{ github.event.head_commit.message }}
          files: |
            SmartSpin2k-*.zip


      
