name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Ensure changelog is updated
        uses: dangoslen/changelog-enforcer@v2
      - name: Validate changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_depth: 10
          version: Unreleased
      - name: Setup python
        uses: actions/setup-python@v2
      - name: Check pre-commit hooks
        uses: pre-commit/action@v2.0.0

